mpc_planner:
  Q_weights: [30.0, 30.0, 5.0]   # weight for x,y,theta
  R_weights: [1.0, 1.0]          # weight for v,omega
  P_weights: [100.0, 100.0, 20.0]   # weight for x,y,theta
  # max_v: 0.6
  # max_omega: 1.0